# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/andy/workdir/hdmi_tx_ddr3_1pcs_1920_1080_dual_ov5640_640_480_32bit_128burst/hdmi_tx_ddr3.srcs/sources_1/ip/cfg_clock/cfg_clock.xci
# IP: The module: 'cfg_clock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/andy/workdir/hdmi_tx_ddr3_1pcs_1920_1080_dual_ov5640_640_480_32bit_128burst/hdmi_tx_ddr3.srcs/sources_1/ip/cfg_clock/cfg_clock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'cfg_clock'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/andy/workdir/hdmi_tx_ddr3_1pcs_1920_1080_dual_ov5640_640_480_32bit_128burst/hdmi_tx_ddr3.srcs/sources_1/ip/cfg_clock/cfg_clock.xdc
# XDC: The top module name and the constraint reference have the same name: 'cfg_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/andy/workdir/hdmi_tx_ddr3_1pcs_1920_1080_dual_ov5640_640_480_32bit_128burst/hdmi_tx_ddr3.srcs/sources_1/ip/cfg_clock/cfg_clock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cfg_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/andy/workdir/hdmi_tx_ddr3_1pcs_1920_1080_dual_ov5640_640_480_32bit_128burst/hdmi_tx_ddr3.srcs/sources_1/ip/cfg_clock/cfg_clock.xci
# IP: The module: 'cfg_clock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/andy/workdir/hdmi_tx_ddr3_1pcs_1920_1080_dual_ov5640_640_480_32bit_128burst/hdmi_tx_ddr3.srcs/sources_1/ip/cfg_clock/cfg_clock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'cfg_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/andy/workdir/hdmi_tx_ddr3_1pcs_1920_1080_dual_ov5640_640_480_32bit_128burst/hdmi_tx_ddr3.srcs/sources_1/ip/cfg_clock/cfg_clock.xdc
# XDC: The top module name and the constraint reference have the same name: 'cfg_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/andy/workdir/hdmi_tx_ddr3_1pcs_1920_1080_dual_ov5640_640_480_32bit_128burst/hdmi_tx_ddr3.srcs/sources_1/ip/cfg_clock/cfg_clock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cfg_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
