# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/andy/workdir/hdmi_tx_ddr3/hdmi_tx_ddr3.srcs/sources_1/ip/afifo_32i_128o_2048/afifo_32i_128o_2048.xci
# IP: The module: 'afifo_32i_128o_2048' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/andy/workdir/hdmi_tx_ddr3/hdmi_tx_ddr3.srcs/sources_1/ip/afifo_32i_128o_2048/afifo_32i_128o_2048.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_32i_128o_2048'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/andy/workdir/hdmi_tx_ddr3/hdmi_tx_ddr3.srcs/sources_1/ip/afifo_32i_128o_2048/afifo_32i_128o_2048_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_32i_128o_2048'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/andy/workdir/hdmi_tx_ddr3/hdmi_tx_ddr3.srcs/sources_1/ip/afifo_32i_128o_2048/afifo_32i_128o_2048_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_32i_128o_2048'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/andy/workdir/hdmi_tx_ddr3/hdmi_tx_ddr3.srcs/sources_1/ip/afifo_32i_128o_2048/afifo_32i_128o_2048.xci
# IP: The module: 'afifo_32i_128o_2048' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/andy/workdir/hdmi_tx_ddr3/hdmi_tx_ddr3.srcs/sources_1/ip/afifo_32i_128o_2048/afifo_32i_128o_2048.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_32i_128o_2048'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/andy/workdir/hdmi_tx_ddr3/hdmi_tx_ddr3.srcs/sources_1/ip/afifo_32i_128o_2048/afifo_32i_128o_2048_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_32i_128o_2048'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/andy/workdir/hdmi_tx_ddr3/hdmi_tx_ddr3.srcs/sources_1/ip/afifo_32i_128o_2048/afifo_32i_128o_2048_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_32i_128o_2048'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
