set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
############## clock define##################
create_clock -period 5 [get_ports sys_clk_p]
set_property PACKAGE_PIN V4 [get_ports sys_clk_p]
set_property IOSTANDARD DIFF_SSTL15 [get_ports sys_clk_p]
###############reset key define##################
set_property PACKAGE_PIN T20 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
#############SPI Configurate Setting##################
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]

set_property PACKAGE_PIN K19 [get_ports hdmi_scl]
set_property PACKAGE_PIN K18 [get_ports hdmi_sda]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_scl]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_sda]

set_property PACKAGE_PIN W19 [get_ports hdmi_tx_clk]
set_property PACKAGE_PIN AB21 [get_ports {hdmi_td[0]}]
set_property PACKAGE_PIN Y22 [get_ports {hdmi_td[1]}]
set_property PACKAGE_PIN Y21 [get_ports {hdmi_td[2]}]
set_property PACKAGE_PIN V19 [get_ports {hdmi_td[3]}]
set_property PACKAGE_PIN V18 [get_ports {hdmi_td[4]}]
set_property PACKAGE_PIN W22 [get_ports {hdmi_td[5]}]
set_property PACKAGE_PIN W21 [get_ports {hdmi_td[6]}]
set_property PACKAGE_PIN T18 [get_ports {hdmi_td[7]}]
set_property PACKAGE_PIN R18 [get_ports {hdmi_td[8]}]
set_property PACKAGE_PIN P17 [get_ports {hdmi_td[9]}]
set_property PACKAGE_PIN N17 [get_ports {hdmi_td[10]}]
set_property PACKAGE_PIN W20 [get_ports {hdmi_td[11]}]
set_property PACKAGE_PIN L13 [get_ports {hdmi_td[12]}]
set_property PACKAGE_PIN M13 [get_ports {hdmi_td[13]}]
set_property PACKAGE_PIN M16 [get_ports {hdmi_td[14]}]
set_property PACKAGE_PIN M15 [get_ports {hdmi_td[15]}]
set_property PACKAGE_PIN K14 [get_ports {hdmi_td[16]}]
set_property PACKAGE_PIN K13 [get_ports {hdmi_td[17]}]
set_property PACKAGE_PIN L20 [get_ports {hdmi_td[18]}]
set_property PACKAGE_PIN L19 [get_ports {hdmi_td[19]}]
set_property PACKAGE_PIN N19 [get_ports {hdmi_td[20]}]
set_property PACKAGE_PIN N18 [get_ports {hdmi_td[21]}]
set_property PACKAGE_PIN M22 [get_ports {hdmi_td[22]}]
set_property PACKAGE_PIN N22 [get_ports {hdmi_td[23]}]
set_property PACKAGE_PIN AB22 [get_ports hdmi_tx_de]
set_property PACKAGE_PIN AA20 [get_ports hdmi_tx_hs]
set_property PACKAGE_PIN AA21 [get_ports hdmi_tx_vs]


set_property IOSTANDARD LVCMOS33 [get_ports hdmi_tx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_td[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_tx_de]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_tx_hs]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_tx_vs]

set_property PACKAGE_PIN B17 [get_ports {cmos1_pclk}]
set_property PACKAGE_PIN F18 [get_ports {cmos1_href}]
set_property PACKAGE_PIN F20 [get_ports {cmos1_vsync}]
set_property PACKAGE_PIN E18 [get_ports {cmos1_rst_n}]
set_property PACKAGE_PIN G21 [get_ports {cmos1_sda}]
set_property PACKAGE_PIN B18 [get_ports {cmos1_scl}]

set_property PACKAGE_PIN C15 [get_ports {cmos1_data[9]}]
set_property PACKAGE_PIN C14 [get_ports {cmos1_data[8]}]
set_property PACKAGE_PIN B20 [get_ports {cmos1_data[7]}]
set_property PACKAGE_PIN A20 [get_ports {cmos1_data[6]}]
set_property PACKAGE_PIN A18 [get_ports {cmos1_data[5]}]
set_property PACKAGE_PIN E19 [get_ports {cmos1_data[4]}]
set_property PACKAGE_PIN G22 [get_ports {cmos1_data[3]}]
set_property PACKAGE_PIN A19 [get_ports {cmos1_data[2]}]
set_property PACKAGE_PIN F19 [get_ports {cmos1_data[1]}]
set_property PACKAGE_PIN D19 [get_ports {cmos1_data[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports cmos1_scl]
set_property IOSTANDARD LVCMOS33 [get_ports cmos1_sda]
set_property IOSTANDARD LVCMOS33 [get_ports cmos1_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports cmos1_pclk]
set_property IOSTANDARD LVCMOS33 [get_ports cmos1_vsync]
set_property IOSTANDARD LVCMOS33 [get_ports cmos1_href]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_data[*]}]


set_property PACKAGE_PIN E16 [get_ports {cmos2_pclk}]
set_property PACKAGE_PIN A15 [get_ports {cmos2_href}]
set_property PACKAGE_PIN A14 [get_ports {cmos2_vsync}]
set_property PACKAGE_PIN A16 [get_ports {cmos2_rst_n}]
set_property PACKAGE_PIN D16 [get_ports {cmos2_sda}]
set_property PACKAGE_PIN D17 [get_ports {cmos2_scl}]

set_property PACKAGE_PIN F13 [get_ports {cmos2_data[9]}]
set_property PACKAGE_PIN E17 [get_ports {cmos2_data[8]}]
set_property PACKAGE_PIN E13 [get_ports {cmos2_data[7]}]
set_property PACKAGE_PIN F16 [get_ports {cmos2_data[6]}]
set_property PACKAGE_PIN B15 [get_ports {cmos2_data[5]}]
set_property PACKAGE_PIN B16 [get_ports {cmos2_data[4]}]
set_property PACKAGE_PIN F14 [get_ports {cmos2_data[3]}]
set_property PACKAGE_PIN E14 [get_ports {cmos2_data[2]}]
set_property PACKAGE_PIN D15 [get_ports {cmos2_data[1]}]
set_property PACKAGE_PIN D14 [get_ports {cmos2_data[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports cmos2_scl]
set_property IOSTANDARD LVCMOS33 [get_ports cmos2_sda]
set_property IOSTANDARD LVCMOS33 [get_ports cmos2_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports cmos2_pclk]
set_property IOSTANDARD LVCMOS33 [get_ports cmos2_vsync]
set_property IOSTANDARD LVCMOS33 [get_ports cmos2_href]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_data[*]}]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets cmos1_pclk_IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets cmos2_pclk_IBUF]